server:
  port: 8081

spring:
  datasource:

    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1221
    url: jdbc:mysql://localhost:3306/ashitaka?useUnicode=true&characterEncoding=UTF-8&useSSL=false


    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 配置初始化大小、最小、最大
      initial-size: 10
      min-idle: 10
      max-active: 20
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒( MinEvictableIdleTimeMillis)
      min-evictable-idle-time-millis: 300000
      #MaxEvictableIdleTimeMillis
      max-evictable-idle-time-millis: 3330000
      #测试连接
      validation-query: SELECT 'x'
      #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
      test-while-idle: true
      #获取连接时执行检测，建议关闭，影响性能
      test-on-borrow: false
      #归还连接时执行检测，建议关闭，影响性能
      test-on-return: false
      #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
      pool-prepared-statements: false
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      max-pool-prepared-statement-per-connection-size: -1
      # spring监控
      aop-patterns: com.ashitaka.api.mapper.*

      #配置扩展插件，常用的插件有=>stat:监控统计  log4j:日志  wall:防御sql注入  下面配好了，(二选一)
      #      filters: stat,wall,slf4j
      #
      #      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录   下面也配好了
      #      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

      # Druid WebStatFilter配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.gif,*.png,*.jpg,*.html,*.js,*.css,*.ico,/druid/*'
      # Druid StatViewServlet配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin
      # 配置日志输出
      filter:
        stat:
          enabled: true
          # 慢查询日志
          log-slow-sql: true
          # 超过时间就是慢查询 毫秒
          slow-sql-millis: 1
          merge-sql: true
        wall:
          enabled: true
          config:
            update-allow: true #允许更新操作
            drop-table-allow: false #禁止删表操作
            insert-allow: true #允许插入操作
            delete-allow: true #删除数据操作


#        slf4j:
#          enabled: true
#          statement-create-after-log-enabled: true
#          statement-close-after-log-enabled: true
#          result-set-open-after-log-enabled: true
#          result-set-close-after-log-enabled: true
