server:
  port: 80

spring:
  application:
    name: ashitaka
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: admin
      web-stat-filter:
        enabled: true
      aop-patterns: com.ryb.ashitaka.sys.mapper    #配错会报错
    dynamic:
      druid: #以下是全局默认值，可以全局更改
        #监控统计拦截的filters
        filters: stat,wall
        #配置初始化大小/最小/最大
        initial-size: 5
        min-idle: 5
        max-active: 10
        #获取连接等待超时时间
        max-wait: 60000
        #间隔多久进行一次检测，检测需要关闭的空闲连接
        time-between-eviction-runs-millis: 60000
        #一个连接在池中最小生存的时间
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1 from dual
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
        pool-prepared-statements: false
        max-pool-prepared-statement-per-connection-size: 20
        stat:
          merge-sql: false
          log-slow-sql: true
          slow-sql-millis: 1
      primary: ds1
      datasource:
        ds1:
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: root
          url: jdbc:mysql://localhost:3306/ashitaka
#        ds2:
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          username: root
#          password: root
#          url: jdbc:mysql://localhost:3306/ashitaka1
#          druid: # 以下参数针对每个库可以重新设置druid参数
#            validation-query: SELECT '2' #比如oracle就需要重新设置这个
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
executor:
  thread-pool:
    core-pool-size: 10 # 核心线程数量
    max-pool-size: 30 # 最大线程数量
    queue-capacity: 100 # 队列长度
    keep-alive-seconds: 60 # 存活时间
    prefix-name: "taskExecutor-" # 线程名称前缀
